### ISSUE TITLE
Error when clicking on "general" tab in settings

### ISSUE THREAD

**Issue by 0kie** [dsrkafuu/skyline-overlay#12]
The overlay crashes when clicking on the "General" tab in settings with the following error:

"Skyline Overlay: BrowserConsole: Uncaught TypeError: Cannot read property 'text' of undefined (Source: https://skyline.dsrkafuu.su/assets/vendor.dc2dac6f.js, Line: 27)"

**Comment by dsrkafuu** [comment]
Fixed in https://github.com/dsrkafuu/skyline-overlay/commit/7c2e6cca4e5e78eb8f1b3597c10f19fb1945677b 😊
