### ISSUE TITLE
Clicking on a text input field freezes the overlay

### ISSUE THREAD

**Issue by Jessidhia** [dsrkafuu/skyline-overlay#16]
**Describe the bug**
When you click on a text input field (tested "Pet Merging ID", "Custom ID"), the entire overlay freezes and stops responding to any input.

**To Reproduce**

1. Click ⚙️ icon
2. Go to Display tab
3. Click on the "Custom ID" field (default value "YOU")
4. Everything freezes

**Expected behavior**
Text to be editable

**Additional context**
When this happens, most of the controls in the OverlayPlugin work either. Toggling "Force white background" does nothing, as does clicking "Reload overlay"; but toggling "Enable overlay" off and on again does reload the overlay. The likely reason is an infinite loop in the javascript that locks the UI thread.

**Comment by dsrkafuu** [comment]
![20211205105924](https://user-images.githubusercontent.com/21136293/144731926-e8826276-fced-46d3-a611-02d7fd3acbb3.png)

Unable to reproduce the problem with ACT 3.5.0.273 and OverlayPlugin 0.17.2.

Theoretically, clicking on the input box in the Overlay window will bring up a prompt dialog, which is to prevent the problem of not being able to enter text properly in the game.

Can you open the Debug Tool (Chrome Dev Tool) in the OverlayPlugin to see if there is any output from the console?

**Comment by Jessidhia** [comment]
The Debug Tool itself also freezes when I attempt to open it. Not even the DOM inspector works once it has entered the frozen state...

Although, once I updated the FFXIV plugin beta once more and restarted ACT, the prompt seems to be working again. Very strange 😥
