### ISSUE TITLE
critical and direct hits shown on the bottom are reversed.

### ISSUE THREAD

**Issue by th411d** [dsrkafuu/skyline-overlay#18]
**Describe the bug**
critical and direct hits shown on the bottom are reversed.

**To Reproduce**

1. Attack the dummy.
2. Measure DPS
3. Check the critical and direct hit values
4. Critical and direct hit percentages are displayed backwards.

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/594899820976668673/918849417673576508/unknown.png)

**Additional context**

**Comment by dsrkafuu** [comment]
Should works after bf1c8ed. 🤗
