### ISSUE TITLE
suggestion for main menu bar

### ISSUE THREAD

**Issue by qnaugthai25** [dsrkafuu/skyline-overlay#19]
the name of trial/raid sometimes is too long and overlapped with the dps meter, would be great if i can hide the name
https://imgur.com/a/lOFlZ3Z

**Comment by dsrkafuu** [comment]
Fixed in 0ff15bc, the hiding option may added later. 🤗

**Comment by dsrkafuu** [comment]
Optimized in 6b7d586.
If inner text (zone name) is too long, show full zone name when mouse hovered.
