### ISSUE TITLE
Error when trying to enable overlay

### ISSUE THREAD

**Issue by 0kie** [dsrkafuu/skyline-overlay#20]
When I try to enable I get the following error

[18/01/2022 03:56:21] Info: SkylineOverlay: BrowserConsole: Uncaught TypeError: Cannot read properties of undefined (reading 'translation') (Source: https://skyline.dsrkafuu.net/assets/index.1522fa93.js, Line: 1)

**Comment by dsrkafuu** [comment]
> When I try to enable I get the following error
> 
> [18/01/2022 03:56:21] Info: SkylineOverlay: BrowserConsole: Uncaught TypeError: Cannot read properties of undefined (reading 'translation') (Source: https://skyline.dsrkafuu.net/assets/index.1522fa93.js, Line: 1)

I'm sorry that I can't reproduce this problem in my local environment at the moment.

I would like to have more detailed information about this, for example:

In ACT's overlay plugin, click on the Open Debug Tool to open Chrome DevTools.
Switch to the Console Tab to see the detailed error stack for this issue (Maybe make a screenshot or something).

![20220118152506](https://user-images.githubusercontent.com/21136293/149890026-b957f8ba-1b9d-4554-af0b-e5ae69b636d4.png)

**Comment by 0kie** [comment]
![Advanced_Combat_Tracker_18-01-2022_13-40-24](https://user-images.githubusercontent.com/82538043/149980231-35e15aa8-1060-4765-a817-3f55675333ea.png)

**Comment by dsrkafuu** [comment]
Thanks for your help, fixed in commit 236e9b2.

Should work well after CloudFlare's CDN Cache is flushed (to v3.1.5).

**Comment by 0kie** [comment]
Can confirm it is working now :)
