### ISSUE TITLE
Option to highlight your own DPS

### ISSUE THREAD

**Issue by Slightlyxz** [dsrkafuu/skyline-overlay#3]
Would it be possible for you to add a option to have your own DPS highlighted, in a color specified in the themes file?
Kind of like Horizoverlay shows your own DPS in white.

Also maybe the option to display HPS, again like in Horizoverlay.

Loving the overlay so far.

**Comment by dsrkafuu** [comment]
Thanks for the suggestion, I will be finishing this feature soon. 😄

For the HPS display, I'm working on settings for a custom main display prop and sub display prop, which allows you to customize how the data is shown.
