### ISSUE TITLE
Colors are not reflected when JRound theme is used.

### ISSUE THREAD

**Issue by th411d** [dsrkafuu/skyline-overlay#32]
**Describe the bug**
Colors are not reflected when JRound theme is used.

**To Reproduce**

3. DPS for you and your PT members will be displayed in black

**Expected behavior**
I would like the colors to reflect the colors that were on v3.6.0.

**Comment by dsrkafuu** [comment]
Fixed in v3.7.1 https://github.com/dsrkafuu/skyline-overlay/commit/2e7781eec301f4eb7d112de2c5e64bb5b2f183e6
