### ISSUE TITLE
Players per row feature

### ISSUE THREAD

**Issue by JamesAndrewsXV** [dsrkafuu/skyline-overlay#33]
Add a players per row feature such that when a player count exceeds the row limit, it starts a new one. 

Alternatively, set a row and column limit or even a hard coded 4x2 version of the meter.

**Comment by dsrkafuu** [comment]
Working on this soon, there should be a "vertical limit" as we currently only have a "horizontal limit".

**Comment by JamesAndrewsXV** [comment]
Great to hear! This would be my favorite feature by far, love everything else about this overlay.

**Comment by JamesAndrewsXV** [comment]
Hey there!

Just wanted to reach out to say thanks to https://github.com/WorstPirateYouEverSeen at https://github.com/bsides/horizoverlay/issues/161, I was able to figure out how to get the overlay to behave the way I was looking for via the devtools element.

Simply put, it seems I can get a 4x2 overlay by doing two things: enabling flex wrap in the "combatants" class, and manipulating the width of the overlay

![image](https://user-images.githubusercontent.com/33642809/213026017-79ba76f6-1e9e-461c-a15a-2de3cf54912e.png)

![image](https://user-images.githubusercontent.com/33642809/213026235-d57f549c-3c7d-4a24-8ea8-ccf5d251ca99.png)

Couple issues arise though.

One, the width value behaves differently depending on the theme. It seems that for a clean 4x2 overlay on the JRound theme, it requires a width of 75%, whereas for the rest of the themes, it transitions into 4x2 at 74% width.

![image](https://user-images.githubusercontent.com/33642809/213027028-4db21431-1c44-4621-a239-d6f479da9c30.png)

The second issue, which I assume is because the combatants element's width is inherited from and tied to the root, is that the width affects the entire overlay, so the status bar and settings are cut off.

![image](https://user-images.githubusercontent.com/33642809/213027377-69c32f85-8b84-45d7-8505-e83b5b44b478.png)

The last thing, I'm sure you're aware of, is that because we did these edits in devtools, it only persists on that instance of the overlay and resets to normal after ACT closes or the overlay is disabled and reenabled.

This is a real quick n dirty edit, and I have some HTML knowledge so I can look into it for ya, but I thought I'd keep you updated on what we found.

**Comment by dsrkafuu** [comment]
Added in v3.8.0.
