### ISSUE TITLE
Encounter history bugged by current time of day display

### ISSUE THREAD

**Issue by Hexerin** [dsrkafuu/skyline-overlay#34]
**Describe the bug**
When attempting to view previous encounters using the encounter history feature, the history will revert to the most recent encounter within 1 second. This is due to the current time of day display updating. As there is little reason to have such a display, simply removing it will likely fix the issue.

**To Reproduce**

1. Click settings cog wheel.
2. Click the History tab.
3. Click on a previous encounter in the list.
4. Watch as it reverts to the most recent counter the moment the time of day display advances by 1 second.

**Expected behavior**
Would expect clicking on a previous encounter would allow viewing of that encounter's results.

**Screenshots**
![issue](https://user-images.githubusercontent.com/42397404/197202740-428f239e-a9c1-4236-974d-6a57b186ba04.jpg)

**Comment by dsrkafuu** [comment]
https://github.com/dsrkafuu/skyline-overlay/blob/main/src/store/slices/api.ts#L49-L69
This should be considered opinionated behavior (for now).

Once ACT pushes new data to the overlay, the history view will be reset to the current one.
You can only keep in the history view state when the encounter is not active.
This may become an option in settings in next version.

I also noticed a theme-specific style issue in the screenshot though.
When the encounter is active, the time on the encounter bar should appear as a different color.

**Comment by dsrkafuu** [comment]
@Hexerin 
What's weird is that I was not able to reproduce the issue at all.
I'll try more these days and figure out the problem.

https://user-images.githubusercontent.com/21136293/197330775-f54c063e-f146-4e10-ac71-7c9f2c4559ee.mp4

**Comment by dsrkafuu** [comment]
Version 3.7.4 now has several debug loggers.

Checkout the README for how to get debug logs.
https://github.com/dsrkafuu/skyline-overlay#online-debug

This will probably help.

**Comment by Kazicoon** [comment]
I'm having this issue

**Comment by Kazicoon** [comment]
Is there any wayto fix this issue? I really want to use this skin

**Comment by Kazicoon** [comment]
> Version 3.7.4 now has several debug loggers.
> 
> Checkout the README for how to get debug logs. https://github.com/dsrkafuu/skyline-overlay#online-debug
> 
> This will probably help.

I tried this and it still doesn't work for me

**Comment by Kazicoon** [comment]
> I think there's been a misunderstanding in communication or something. This isn't a feature/enhancement request. This is reporting an actual bug/issue with the overlay. Here's video to more clearly show the issue, including showing that it persists with your native theme design:
> 
>  Final.Fantasy.XIV.A.Realm.Reborn.2022.10.21.-.16.40.18.01.webm

Is tere a fix to this out yet?

**Comment by Kazicoon** [comment]
> @Hexerin What's weird is that I was not able to reproduce the issue at all. I'll try more these days and figure out the problem.
> 
>  2022-10-22.16-53-00_x264.mp4

I can confirm it is doing it as well for me

**Comment by Kazicoon** [comment]
> I think there's been a misunderstanding in communication or something. This isn't a feature/enhancement request. This is reporting an actual bug/issue with the overlay. Here's video to more clearly show the issue, including showing that it persists with your native theme design:
> 
>  Final.Fantasy.XIV.A.Realm.Reborn.2022.10.21.-.16.40.18.01.webm


https://user-images.githubusercontent.com/97134898/200304538-00ca176d-3a94-4f72-892c-1177a226cdd1.mp4

**Comment by dsrkafuu** [comment]
The only thing which resets the history view is `state.history.idx = -1` in Line 56 & 68 in api store:
https://github.com/dsrkafuu/skyline-overlay/blob/main/src/store/slices/api.ts#L50-L74

Which is part of these actions:
- `updateCombat`: triggered by new combat data from ACT
- `showHistory`: only triggered by click of history row in history tab

So, one possible reason I'm guessing is that the ACT keeps sending combat data to the overlay window, even after escaping the battle. But there could still be other reasons.

Since I was unable to get a global server account to verify my conjecture, or find out the real reason, I hoped to locate the problem through the relevant log. You can refer to [the instructions in the README](https://github.com/dsrkafuu/skyline-overlay#online-debug) to upload the .log file when the problem occurs.

**Comment by dsrkafuu** [comment]
Finally found the issue and fixed it in 4db4e4da.
