### ISSUE TITLE
Encounter history should state encounter name, not zone name

### ISSUE THREAD

**Issue by Hexerin** [dsrkafuu/skyline-overlay#35]
**Is your feature request related to a problem? Please describe.**
I wouldn't say a "problem", but it would be easier to select a specific encounter (1st boss of dungeon, 2nd boss of dungeon, etc) if the encounter history used the encounter name displayed in ACT.

**Describe the solution you'd like**
I would like the encounter history to show encounter name, not zone name.

**Describe alternatives you've considered**
There's not really an alternative for this request, as it's a very specific request.

**Additional context**
So for example, instead of "The Goblet", it would say "Striking Dummy".

![asdf1](https://user-images.githubusercontent.com/42397404/197306434-aece2eab-9abd-40c4-b957-a1a1e96dc946.jpg)
![asdf2](https://user-images.githubusercontent.com/42397404/197306436-9fe22820-6a67-4a74-8a4f-4cb0c4c34dc2.jpg)

**Comment by dsrkafuu** [comment]
Finally found the issue and fixed it in 4db4e4da (v3.8.0).
