### ISSUE TITLE
Encounter History not working properly

### ISSUE THREAD

**Issue by Kazicoon** [dsrkafuu/skyline-overlay#36]
**Describe the bug**
When I check the history for the fights in the overlay, if I select one it automatically moves back to the previous pull not allowing me to check the other fighrts in the history
**To Reproduce**

1. Go into a encounter
2. Do 2 pulls to have 2 logs in your history
3. Select the 2nd pull in the history
4. It will automatically go back to the last pull in the history

**Expected behavior**
It is supposed to allow me to check the history of previous pulls 
**Screenshots**
**Additional context**
Gif of the issue occuring
https://imgur.com/VfLxw0y

**Comment by Kazicoon** [comment]
Any kind of help would be amazing

**Comment by Kazicoon** [comment]
If anyone can help me with this issue please feel free to message me on disc at KaziTrashPanda#8846

**Comment by dsrkafuu** [comment]
Finally found the issue and fixed it in 4db4e4da (v3.8.0).
