### ISSUE TITLE
Incorrect number display

### ISSUE THREAD

**Issue by EmrysSai** [dsrkafuu/skyline-overlay#39]
- Bug description
I think the damage number display is incorrect when you choose the big number mode in Chinese version. It confuses one thousand (1000) with ten thousand (10000).

- Steps to reproduce the bug
1. Go to 'data'
2. Click on 'Big data mode'
3. See error

- Expected behavior

- Screenshots
Correct in normal mode
![image](https://github.com/dsrkafuu/skyline-overlay/assets/23381840/7bbfb62e-df57-4e41-a740-f160ec1bded9)
Incorrect in big number mode
![image](https://github.com/dsrkafuu/skyline-overlay/assets/23381840/d030b205-667f-4bd5-87ad-a055067e978e)

**Comment by dsrkafuu** [comment]
中文OK

这个玩意其实是这样的，小吉6.0不是玩数值压缩吗，结果搞得群友打本很难受
在群友的要求下搞了个数字x10的模式，模拟5.X玩😂

改天改下文案，改成娱乐模式会好点
