### ISSUE TITLE
请问可以添加7.0新职业的图标吗

### ISSUE THREAD

**Issue by AnyoneCn** [dsrkafuu/skyline-overlay#48]
![image](https://github.com/dsrkafuu/skyline-overlay/assets/86087425/6ebaee14-2b7b-4045-9913-aed2f0c4396e)
![image](https://github.com/dsrkafuu/skyline-overlay/assets/86087425/763d41c6-9077-4a59-808e-bc2e80b80a7d)

**Comment by dsrkafuu** [comment]
周二已经更新了，用官方地址就行 https://skyline.dsrkafuu.net/
