### ISSUE TITLE
Problem with Websocket Overlay

### ISSUE THREAD

**Issue by Slightlyxz** [dsrkafuu/skyline-overlay#6]
Not sure if I'm just using it wrong, but the Websocket Overlay doesn't seem to work.

For Horizoverlay and Kagerou I added /?HOST_PORT=ws://127.0.0.1:10501/ behind the provided URL of the overlay, which worked, when trying to use https://skyline.dsrkafuu.su/?HOST_PORT=ws://127.0.0.1:10501/ the overlay isn't working inside my browser.

Tried different browsers

In the screenshot I used 2 browser tabs with the following urls: 
https://skyline.dsrkafuu.su/?HOST_PORT=ws://127.0.0.1:10501/
https://github.com/bsides/horizoverlay/?HOST_PORT=ws://127.0.0.1:10501/

Horizoverlay was working inside the browser, whilst Skyline-Overlay wasn't.
![Screenshot Horizo working](https://user-images.githubusercontent.com/80231852/110424561-47596e80-80a3-11eb-8928-a6126461a605.png)

**Comment by dsrkafuu** [comment]
@Slightlyxz 
Can you try these two below?

```
https://skyline.dsrkafuu.su/?OVERLAY_WS=ws://127.0.0.1:10501/
https://skyline.dsrkafuu.su/?OVERLAY_WS=ws://127.0.0.1:10501/ws
```

Please let me know if any of these work.

**Comment by Slightlyxz** [comment]
https://skyline.dsrkafuu.su/?OVERLAY_WS=ws://127.0.0.1:10501/ws 

Works, thank you!
